import VisitStatus from './VisitStatus';
import Skill from './Skill';

export default interface Visit {
    id: number;
    order: number;
    trackingId: string;
    status: VisitStatus;
    title: string;
    address: string;
    latitude: string;
    longitude: string;
    load: number;
    load2: number;
    load3: number;
    windowStart: string;
    windowEnd: string;
    windowStart2: string;
    windowEnd2: string;
    duration: number;
    contactName: string;
    contactPhone: string;
    contactEmail: string;
    reference: string;
    notes: string;
    skillsRequired: Skill[];
    skillsOptional: Skill[];
    plannedDate: string;
    routeId: string;
    routeEstimatedTimeStart: string;
    estimatedTimeArrival: string;
    estimatedTimeDeparture: string;
    checkinTime: string;
    checkoutTime: string;
    checkoutLatitude: string;
    checkoutLongitude: string;
    checkoutComment: string;
    checkoutObservation: string;
    signature: string;
    pictures: string;
    created: string;
    modified: string;
    etaPredicted: string;
    etaCurrent: string;
    driverId: number;
    vehicleId: number;
    priority: boolean;
    hasAlert: boolean;
    priorityLevel: number;
    extrafieldValues?: any;
}
